# Generated by Django 4.1.5 on 2024-01-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Scheme_closing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('defective_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('MNO_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('guidelines', models.CharField(blank=True, max_length=255, null=True)),
                ('guidelinelink', models.CharField(blank=True, max_length=255, null=True)),
                ('faq_link', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
