# Generated by Django 4.1.5 on 2024-01-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='loggers',
            fields=[
                ('scholarship_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.scholarship')),
                ('is_selected', models.BooleanField(blank=True, null=True)),
            ],
            bases=('myapp.scholarship',),
        ),
    ]
