# Generated by Django 4.1.5 on 2024-01-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_loggers_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggers',
            name='is_selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
