# Generated by Django 4.1.5 on 2024-01-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_loggers_user_loggers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggers',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
