# Generated by Django 4.1.5 on 2024-01-11 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_loggers_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggers',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
