# Generated by Django 4.1.5 on 2024-01-11 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_loggers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggers',
            name='user',
        ),
        migrations.AddField(
            model_name='loggers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
