# Generated by Django 4.1.5 on 2024-01-11 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_loggers_user_loggers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggers',
            name='user',
        ),
        migrations.AddField(
            model_name='loggers',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
