# Generated by Django 4.1.5 on 2024-01-25 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_loggers_user_loggers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scholarship')},
            },
        ),
    ]
